[package]
name = "snapper"
version = "0.1.0"
edition = "2021"

# Shared Package Configuration
authors = { workspace = true }
license = { workspace = true }

[features]
default = [ "drawing" ]
drawing = [ "dep:imageproc" ]

[dependencies]
anyhow = { workspace = true }
geo = { workspace = true }
image = { workspace = true }
imageproc = { workspace = true, optional = true }
thiserror = { workspace = true }
