[package]
name = "snapper"
version = "0.1.0"
edition = "2021"

# Shared Package Configuration
authors = { workspace = true }
license = { workspace = true }

[dependencies]
anyhow = { workspace = true }
geo = { workspace = true }
image = { workspace = true }
thiserror = { workspace = true }
