[package]
name = "snapper"
version = "0.1.0"
edition = "2021"

# Shared Package Configuration
authors = { workspace = true }
license = { workspace = true }

[dependencies]
anyhow = "1.0.89"
geo = "0.28.0"
image = { version = "0.25.2", default-features = false, features = ["jpeg", "png"] }
thiserror = "1.0.64"
